version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install

  build:
    commands:
      - npm run lint
      - npm run build

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - dist/**/*
    - package.json
    - package-lock.json
    - node_modules/**/*
    - .ebextensions/**/*
    - .platform/**/*
  discard-paths: no

cache:
  paths:
    - node_modules/**/*
